# Generated by Django 3.2.4 on 2021-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], default='student', max_length=10)),
                ('Contact_no', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='user_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
